helm: support external database
Make database deployment optional. Support configuring a connection to
an external database on given host and port for api and backup job.

diff --git a/helm_charts/pebbles/templates/backup-db-cronjob.yaml b/helm_charts/pebbles/templates/backup-db-cronjob.yaml
--- a/helm_charts/pebbles/templates/backup-db-cronjob.yaml
+++ b/helm_charts/pebbles/templates/backup-db-cronjob.yaml
@@ -33,8 +33,13 @@ spec:
                   start_ts=$(date +%s)
                   echo "$(date -Is) backup starting"
 
-                  echo "$(date -Is) first check that db is responding"
-                  if pg_isready; then true; else echo "$(date -Is) cannot connect to db"; exit 1; fi
+                  echo "$(date -Is) first check that database $PGHOST:$PGPORT is responding"
+                  if pg_isready; then
+                    echo "$(date -Is) connection test ok"
+                  else
+                    echo "$(date -Is) cannot connect to database"
+                    exit 1
+                  fi
 
                   # construct backup file name
                   BACKUP_DIR=/backup/{{ .Values.backup.name }}
@@ -77,7 +82,9 @@ spec:
 
               env:
                 - name: PGHOST
-                  value: db
+                  value: "{{ .Values.databaseHost }}"
+                - name: PGPORT
+                  value: "{{ .Values.databasePort }}"
                 - name: PGDATABASE
                   value: pebbles
                 - name: PGUSER
