helm charts: improve backup job
- check for database connection in the start to avoid dumping encrypted
  error messages instead of database contents
- add backup value structure in values.yaml

diff --git a/helm_charts/pebbles/templates/backup-db-cronjob.yaml b/helm_charts/pebbles/templates/backup-db-cronjob.yaml
--- a/helm_charts/pebbles/templates/backup-db-cronjob.yaml
+++ b/helm_charts/pebbles/templates/backup-db-cronjob.yaml
@@ -33,6 +33,9 @@ spec:
                   start_ts=$(date +%s)
                   echo "$(date -Is) backup starting"
 
+                  echo "$(date -Is) first check that db is responding"
+                  if pg_isready; then true; else echo "$(date -Is) cannot connect to db"; exit 1; fi
+
                   # construct backup file name
                   BACKUP_DIR=/backup/{{ .Values.backup.name }}
                   BACKUP_FILE_BASE="db-backup"
